CREATE TABLE MEMBER (
	NAME	VARCHAR2(10),
	USERID	VARCHAR2(10),
	PWD		VARCHAR2(10),
	EMAIL	VARCHAR2(20),
	PHONE	CHAR(13),
	ADMIN	NUMBER(1) DEFAULT 0, -- 0: 사용자, 1: 관리자
	JOINDATE DATE DEFAULT sysdate,
	PRIMARY KEY(USERID)
);

ALTER TABLE "MEMBER"
MODIFY NAME VARCHAR2(20);

SELECT sysdate FROM dual;

SELECT * FROM MEMBER;
SELECT * FROM USER_TABLES;
SELECT * FROM USER_TAB_COLUMNS WHERE TABLE_NAME IN ('MEMBER');
SELECT * FROM USER_CONSTRAINTS;